#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#killall -q polybar

xsetroot -cursor_name left_ptr
xset r rate 300 50
nitrogen --restore

bspc config top_padding     0
bspc config bottom_padding     0

picom &
unclutter &
#polybar simple &
setxkbmap -option caps:escape

bspc monitor -d 1 2 3 4

bspc config border_width    0
bspc config window_gap      0
bspc config split_ratio     0.5

bspc rule -a rhubarb state=pseudo_tiled
bspc rule -a feh state=floating

#bspc config normal_border_color "#484848"
#bspc config focused_border_color "#1F8999"

