
[font]
builtin_box_drawing = false
size = 12

[font.normal]
family = "pris"

[window]
dynamic_padding = true
opacity = 1

[env]
TERM = "xterm-256color"

[general]

import = ["/home/juca/.config/alacritty/themes/tokyo-night.toml"]
