[font]
builtin_box_drawing = true
size = 15

[font.normal]
#family = "pris"
#family = "terminus"
#family = "IBM XGA-AI"
#family = "BmPlus IBM XGA-AI 12x20"
#family = "cozette"
family = "iosevka"
#family = "jetbrainsmono"
#family = "cascadia code"

[window]
dynamic_padding = true
opacity = 0.9

[env]
TERM = "xterm-256color"

[general]
import = ["/home/juca/.config/alacritty/themes/catppucin.toml"]

