
[font]
builtin_box_drawing = false
size = 15

[font.normal]
#family = "pris"
family = "terminus"
#family = "IBM XGA-AI"
#family = "BmPlus IBM XGA-AI 12x20"
#family = "cozette"
#family = "iosevka"

[window]
dynamic_padding = true
opacity = 1

[env]
TERM = "xterm-256color"

[general]
#import = ["/home/juca/.config/alacritty/themes/catppucin.toml"]
import = ["/home/juca/.config/alacritty/themes/gruvbox.toml"]

