
[font]
builtin_box_drawing = false
size = 12

[font.normal]
family = "pris"

[window]
dynamic_padding = true
opacity = 0.95

[env]
TERM = "xterm-256color"

[general]
import = ["/home/juca/.config/alacritty/themes/gruvbox.toml"]

[keyboard] # rebind <C-;> to <C-_> for nvim
bindings = [{ key = ";", mods = "Control", chars = "\u001f" }]

