#!/bin/sh

#grep 'size = (\d+)' $HOME/.config/alacritty/alacritty.toml

terminus_sizes=(6 7 8 9 10 11 13 15 16)

var=`cat $HOME/.alacritty_font_size`

if [ $1 = "-i" ]; then
        if [ $var != 8 ]; then
            var=$((var+1))
        fi
else
        if [ $var != 0 ]; then
            var=$((var-1))
        fi
fi

alacritty msg config "font.size=${terminus_sizes[$var]}"

echo $var > $HOME/.alacritty_font_size
